name: Templates

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:

  enter-devshells:
    name: Test devshells
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup
      uses: ./.github/actions/common-setup
      with:
        SECRET_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CACHIX_TOKEN: ${{ secrets.ORGANIST_CACHIX_TOKEN }}

    - name: Run flake checks
      run: |
        nix flake check -L

    - name: Check flake.lock
      run: |
        if git status --porcelain | grep flake.lock; then
          echo "flake.lock was changed:"
          git diff
          exit 1
        fi

    - name: Test devshells
      run: |
        nix run .#run-test template
        nix run .#run-test template -- --full Bash
        find examples -maxdepth 1 -mindepth 1 -type d -print0 -exec nix run .#run-test example {} \;
